# Generated by Django 3.0.5 on 2020-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100)),
                ('nombreinfractor', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('no_economico', models.CharField(max_length=50)),
                ('ruta', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('num_licencia', models.IntegerField()),
                ('motivo', models.CharField(max_length=80)),
                ('garantia', models.CharField(max_length=50)),
                ('arti', models.IntegerField()),
                ('matricula', models.CharField(max_length=50)),
                ('cardcirculacion', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parquimetros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foliopar', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('num_estacionamiento', models.CharField(max_length=50)),
                ('manzana', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('vencimiento', models.CharField(max_length=50)),
                ('nombreinfractor', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('num_permiso', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('foliodepago', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8)),
                ('pas', models.CharField(max_length=8)),
            ],
        ),
    ]
