# Generated by Django 3.0.5 on 2020-05-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='arti',
            field=models.IntegerField(verbose_name='Articulo del Reglamento'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='cardcirculacion',
            field=models.CharField(max_length=50, verbose_name='Numero de Circulacion'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='folio',
            field=models.CharField(max_length=100, verbose_name='Numero de folio'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='no_economico',
            field=models.CharField(max_length=50, verbose_name='Numero del economico'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='nombreinfractor',
            field=models.CharField(max_length=50, verbose_name='Nombre del Infractor'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='num_licencia',
            field=models.IntegerField(verbose_name='Numero de Licencia'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='user',
            field=models.CharField(max_length=8, verbose_name='Nombre del agente'),
        ),
        migrations.AlterField(
            model_name='multas',
            name='folio',
            field=models.CharField(max_length=50, verbose_name='Numero de folio'),
        ),
        migrations.AlterField(
            model_name='multas',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de multa'),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='foliopar',
            field=models.CharField(max_length=100, verbose_name='Numero de folio'),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='Numero de Matricula'),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='nombreinfractor',
            field=models.CharField(max_length=50, verbose_name='Nombre del Infractor'),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='num_estacionamiento',
            field=models.CharField(max_length=50, verbose_name='Numero de Estacionamiento'),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='num_permiso',
            field=models.IntegerField(verbose_name='Numero de permiso'),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='user',
            field=models.CharField(max_length=8, verbose_name='Nombre del agente'),
        ),
    ]
