# Generated by Django 3.0.5 on 2020-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0002_auto_20200513_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parquimetros',
            old_name='foliopar',
            new_name='folio',
        ),
        migrations.RemoveField(
            model_name='infraccion',
            name='num_licencia',
        ),
        migrations.AddField(
            model_name='infraccion',
            name='clave',
            field=models.CharField(default=1234, max_length=100, verbose_name='Clave de accion'),
            preserve_default=False,
        ),
    ]
