# Generated by Django 3.0.5 on 2020-05-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0003_auto_20200521_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquimetros',
            name='fecha',
            field=models.DateField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parquimetros',
            name='hora',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
