# Generated by Django 3.0.5 on 2020-05-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0004_auto_20200522_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parquimetros',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='parquimetros',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='parquimetros',
            name='serie',
        ),
    ]
