# Generated by Django 3.0.5 on 2020-05-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0007_auto_20200522_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquimetros',
            name='fecha',
            field=models.DateField(blank='True', default=20200523, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parquimetros',
            name='hora',
            field=models.CharField(blank='True', max_length=50),
        ),
        migrations.AlterField(
            model_name='parquimetros',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
